name: Build NewPipeCLI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Windows create same temp dir
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "" "org.gradle.jvmargs=-Djava.io.tmpdir=D:/temp" >> gradle.properties
          mkdir D:/temp

      - name: Build native executable
        run: ./gradlew clean nativeCompile
      
      - name: Debug With SSH When fails
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: newpipecli-${{ matrix.os }}
          path: |
            build/distributions/NewPipeCLI.zip
